---
title: "Mapping with Leaflet"
author: "Peter E"
date: "May 1, 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## My First Map
```{r}
library(leaflet)
map<-leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat=39.2980803,lng=-76.5898801,popup = "Jeff's Office")
map


```


## Map with Markers from DF
```{r}
set.seed(42)
df<-data.frame(
  lat=runif(20,min=39.2,max=39.3),
  lng=runif(20,min=-76.6,max=-76.5)
)

map<-leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat=df$lat,lng=df$lng)
map

```


## Custom Icon and Pop Ups
```{r}
set.seed(42)
df<-data.frame(
  lat=runif(3,min=39.2,max=39.3),
  lng=runif(3,min=-76.6,max=-76.5)
)

myIcon<-makeIcon(
  iconUrl = 'https://fontawesome.com/icons/question',
  iconWidth = 30,
  iconHeight = 30
)

links<-c(
  "<a href='https://fontawesome.com/icons/question'>Point 1</a>",
  "<a href='https://cnn.com'>Point 21</a>",
  "<a href='https://npr.org' target=_Blank>Point 3</a>"
)

map<-leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat=df$lat,lng=df$lng,icon = myIcon, popup = links)
  
map
  


```


## Mapping Clusters
If too many points to show at once, use clustering
```{r}
set.seed(42)
df<-data.frame(
  lat=runif(500,min=39.25,max=39.35),
  lng=runif(500,min=-76.65,max=-76.55)
)

map<-df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(clusterOptions = markerClusterOptions())

map

```


## Circle Markers Varying Sizes by Variable
```{r}

#Make df of cities lat long and size
md_cities<-data.frame(
  
    name = c("Baltimore","Frederick","Rockville","Gaithersburg",
    "Bowie","Hagerstown","Annapolis",
    "College Park","Salisbury","Laurel"),
    pop=c(
    619493,66169,62334,61045,55232,39890,38880,30587,30484,25346
    ),
    lat = c(39.292592,39.4143921,39.0840,39.1434,39.0068,39.6418,
    38.9784,38.9897,38.3607,39.0993),
    lng = c(
    -76.6077852,-76.4204875,-76.1528,-76.2014,-76.7791,
    -77.7200,-76.4922,-76.9378,-75.5994,-76.8483
    )

)#End df

#Make map
md_cities %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles(weight = 5, radius = sqrt(md_cities$pop)*30)






```

## Map with Circles and Legend
```{r}

set.seed(42)
df<-data.frame(
  lat=runif(20,min=39.25,max=39.35),
  lng=runif(20,min=-76.65,max=-76.55),
  col = sample(c('red','blue','green'),20,replace = TRUE)
)

df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircleMarkers(color = df$col, weight = 1) %>% 
  addLegend(labels = LETTERS[1:3],colors = c('blue','red','green'))

```



